/**
 * All user-facing copy lives here so it can be reviewed and later translated.
 * UK English throughout.
 */

export const brand = {
  name: "Latchkey",
  tagline: "Self-service arrivals for small hosts",
};

export const marketing = {
  headline: "Your guests let themselves in, calmly, while you get on with your day.",
  subhead:
    "Latchkey handles arrivals, house rules and extras for hosts who let a few rooms across Airbnb, Booking.com, Homestay.com and direct bookings.",
  primaryCta: "See a guest arrival",
  secondaryCta: "Open host dashboard",
  benefits: [
    {
      title: "Check-in without you",
      body: "A QR code, short link or PIN at the door. No app, no sign-up, no waiting on the doorstep at 11pm.",
    },
    {
      title: "Every booking in one list",
      body: "Airbnb, Booking.com, Homestay.com and direct bookings side by side, so you always know who is arriving.",
    },
    {
      title: "Extras that pay for themselves",
      body: "Late check-out, fresh towels, early arrival. Guests request and pay; you approve with one tap or let it run itself.",
    },
  ],
  beforeAfter: {
    beforeTitle: "A Tuesday before Latchkey",
    before: [
      "Three inboxes, three sets of arrival times",
      "Leaving a client call to hand over a key",
      "A towel request at 11pm you see at 7am",
      "Late check-out agreed, cleaner turns up anyway",
    ],
    afterTitle: "A Tuesday with Latchkey",
    after: [
      "One arrivals list for all channels",
      "Guest checks in at the door on the tablet",
      "Requests land in Today, approved in a tap",
      "Late check-out only offered when the room is free",
    ],
  },
};

export const auth = {
  signInTitle: "Welcome back",
  signInBody: "Sign in to see today's arrivals and keep your calendars in step.",
  signUpTitle: "Set up your rooms",
  signUpBody: "Create a host account. It takes a minute and you can explore with demo rooms first.",
  emailLabel: "Email address",
  passwordLabel: "Password",
  signInCta: "Sign in",
  signUpCta: "Create account",
  switchToSignUp: "New here? Create a host account",
  switchToSignIn: "Already have an account? Sign in",
  checkInbox: "Check your inbox to confirm your email address, then sign in.",
  genericError: "Something went wrong. Please try again.",
  signOut: "Sign out",
};

export const hostNav = {
  today: "Today",
  bookings: "Bookings",
  properties: "Properties",
  connections: "Connections",
  services: "Services",
  guides: "Guides",
  settings: "Settings",
};

export const statuses = {
  needs_details: "Needs details",
  upcoming: "Upcoming",
  checked_in: "In stay",
  checked_out: "Checked out",
  cancelled: "Cancelled",
  blocked: "Blocked, not a booking",
  mirror: "Echo of another platform",
  flagged: "Needs a look",
  arriving_today: "Arriving today",
  in_stay: "In stay",
  departing_today: "Departing today",
  past: "Past",
};

export const channels = {
  airbnb: "Airbnb",
  booking_com: "Booking.com",
  homestay: "Homestay.com",
  vrbo: "Vrbo",
  agoda: "Agoda",
  direct: "Direct",
  other: "Other website (.ics link)",
};

/**
 * Where a host finds the calendar export link on each platform.
 * Kept here so the steps can be updated without touching code.
 * `screenshot` is a placeholder for an image to be added later.
 */
export const calendarGuides: Record<
  string,
  { title: string; steps: string[]; helpUrl: string | null; helpLabel: string; note?: string; screenshot: string | null }
> = {
  airbnb: {
    title: "Where do I find my Airbnb calendar link?",
    steps: [
      "Open Calendar and choose the listing.",
      "Go to Availability.",
      "Choose Connect calendars, then Connect to another website.",
      "Copy the Airbnb calendar link.",
    ],
    note: "One link per listing.",
    helpUrl: "https://www.airbnb.co.uk/help/article/99",
    helpLabel: "Airbnb help: sync calendars",
    screenshot: null,
  },
  booking_com: {
    title: "Where do I find my Booking.com calendar link?",
    steps: [
      "Sign in to the Extranet.",
      "Go to Rates & Availability, then Sync calendars.",
      "Choose Add calendar connection.",
      "Copy the Booking.com calendar link.",
    ],
    note: "Calendar sync may not be available for hotel-type properties, or if you already use a channel manager.",
    helpUrl: "https://partner.booking.com/en-gb/help/rates-availability/calendar-sync",
    helpLabel: "Booking.com help: calendar sync",
    screenshot: null,
  },
  vrbo: {
    title: "Where do I find my Vrbo calendar link?",
    steps: [
      "Open your owner dashboard and go to Calendar.",
      "Choose Import/Export.",
      "Choose Export calendar.",
      "Copy the .ics link.",
    ],
    helpUrl: "https://help.vrbo.com/articles/How-do-I-sync-my-calendars",
    helpLabel: "Vrbo help: sync calendars",
    screenshot: null,
  },
  homestay: {
    title: "Where do I find my Homestay.com calendar link?",
    steps: [
      "Open your host dashboard and go to Calendar.",
      "Choose Sync calendar.",
      "Copy the export link.",
    ],
    helpUrl: "https://www.homestay.com/help",
    helpLabel: "Homestay help: synchronise your calendar with a 3rd party",
    screenshot: null,
  },
  agoda: {
    title: "Where do I find my Agoda calendar link?",
    steps: [
      "Sign in to YCS or the Agoda Homes portal.",
      "Go to Calendar.",
      "Choose Calendar sync.",
      "Copy the export link.",
    ],
    helpUrl: "https://ycs.agoda.com",
    helpLabel: "Agoda YCS",
    screenshot: null,
  },
  other: {
    title: "Where do I find my calendar link?",
    steps: [
      "Look for Calendar sync, iCal or Export calendar in your platform's settings.",
      "Copy the export link. It usually ends in .ics.",
    ],
    helpUrl: null,
    helpLabel: "",
    screenshot: null,
  },
  direct: {
    title: "Direct bookings",
    steps: ["Direct bookings are added by hand in Latchkey, so there is no calendar link to paste."],
    helpUrl: null,
    helpLabel: "",
    screenshot: null,
  },
};

export const today = {
  title: "Today",
  subtitle: "Arrivals, departures and anything waiting on you.",
  arriving: "Arriving today",
  inStay: "In stay",
  departing: "Departing today",
  actionRequired: "Needs your details",
  actionBody: "These bookings arrived from a channel without a guest name. Add what you know.",
  noArrivals: "Nobody is arriving today. Enjoy the quiet.",
  noDepartures: "No departures today.",
  noStays: "No guests in the house right now.",
  allClear: "Nothing is waiting on you. Everything is up to date.",
  saveDetails: "Save details",
  doubleBookedTitle: "Possible double-booking",
  doubleBookedBody: "Two platforms show different guests in the same room on the same nights. Check both and cancel one.",
  maybeBlock: "Dates you closed yourself?",
  markBlocked: "Not a booking, mark as blocked",
  cleaningToday: "Cleaning window today",
};

export const bookings = {
  title: "Bookings",
  subtitle: "Every stay across your channels, in one place.",
  guestEmail: "Guest email (optional)",
  guestEmailHint: "Lets the guest confirm who they are at check-in",
  mirrorNote: "Another platform is showing this stay as closed. It is linked to the real booking, so it is not counted twice.",
  listing: "Listing",
  tentative: "The platform marks this stay as not yet confirmed.",
  openOnPlatform: "Open on the platform",
  alsoClosedOn: "Also closed on",
  blockedCell: "Closed",
  listView: "List",
  timelineView: "Timeline",
  addBooking: "Add booking",
  importCsv: "Import bookings",
  empty: "No bookings yet. Add one by hand, import a file, or connect a calendar.",
  filtersRoom: "Room",
  filtersChannel: "Channel",
  filtersStatus: "Status",
  allRooms: "All rooms",
  allChannels: "All channels",
  allStatuses: "All statuses",
  guestUnknown: "Guest name to confirm",
  nights: "nights",
  night: "night",
  editBooking: "Edit booking",
  undoCheckIn: "Undo check-in",
  undoCheckInHelp: "This guest is checked in.",
  undoCheckInConfirm:
    "Undo this check-in? The guest's stay link stops working and they'll need to check in again.",
  undoCheckInDone: "Check-in undone. The booking is back to upcoming.",
  manualNote: "Fields you change here are kept, even when the channel calendar updates.",
  importTitle: "Import bookings from a file",
  importBody: "Upload a CSV export from a channel or spreadsheet, then match the columns.",
  importChoose: "Choose CSV file",
  importConfirm: "Import bookings",
  importedToast: "bookings imported",
};

export const properties = {
  title: "Properties",
  subtitle: "Your rooms, door details and cleaning windows.",
  addProperty: "Add property",
  addRoom: "Add room",
  noProperties: "No properties yet. Add one, or load the demo rooms to have a look around.",
  noRooms: "No rooms in this property yet.",
  guestLink: "Guest link",
  doorPin: "Door PIN",
  quietHours: "Quiet hours",
  checkInWindow: "Check-in and check-out",
  wifi: "Wi-Fi",
  cleaning: "Cleaning and unavailable times",
  addWindow: "Add cleaning window",
  wholeHouse: "Whole house",
  weekly: "Every",
  noWindows: "No cleaning windows set.",
};

export const connections = {
  title: "Connections",
  subtitle: "Calendar links that keep your bookings in step.",
  byRoomTitle: "Each room across platforms",
  byRoomBody: "Link every platform that lets the same room. Latchkey matches the entries so one stay is never counted twice.",
  noLinks: "No calendars linked to this room yet.",
  add: "Add calendar link",
  test: "Test link",
  syncNow: "Sync now",
  syncAll: "Sync all",
  lastSynced: "Last checked",
  never: "Not checked yet",
  empty: "No calendars connected. Paste an iCal link from a channel to start.",
  linkLabel: "Calendar link (iCal)",
  linkHelp: "Your link is stored privately on the server. Only a shortened version is shown here.",
  roomLabel: "Room this calendar belongs to",
  listingLabel: "What the channel calls this listing",
  history: "Recent checks",
  noHistory: "No sync history yet.",
  testOk: "That link works.",
  managerTitle: "Channel manager (Beds24, Smoobu, Hostaway)",
  managerBody: "Direct two-way sync with channel managers is planned for a later stage.",
  comingSoon: "Coming soon",
  conflictTitle: "Something needs your eye",
  syncedToast: "Calendar checked",
  removeConfirm: "Remove this calendar link? Bookings already imported are kept.",
};

export const settings = {
  title: "Settings",
  subtitle: "Your business details and demo content.",
  business: "Your business",
  businessName: "Business name",
  contactEmail: "Contact email",
  contactPhone: "Contact phone",
  currency: "Currency",
  timezone: "Timezone",
  save: "Save changes",
  saved: "Saved",
  demoTitle: "Demo content",
  demoBody:
    "Load The Trinity Rooms in High Wycombe: three rooms, bookings across four channels, and Tuesday and Thursday cleaning windows.",
  loadDemo: "Load demo rooms",
  resetDemo: "Reset demo dates",
  removeDemo: "Remove demo data",
  demoBanner: "You are looking at demo content.",
  removing: "Removing…",
  channelsTitle: "What you call each booking site",
  channelsBody:
    "Guests see these names when they choose where they booked. Rename any of them — for example \"Booked directly\" to \"Our website\". Leave one blank to keep the standard name. Your calendars and reports are unaffected.",
  channelsSaved: "Names saved",
  privacyTitle: "Privacy and retention",
  privacyBody:
    "Guest names, phone digits and notes are cleared 90 days after check-out. Anonymous stay records are kept for your statistics.",
};

export const onboarding = {
  title: "Let's set up your rooms",
  subtitle: "Three short steps. You can change anything later.",
  step1: "Property",
  step2: "Rooms",
  step3: "Arrivals",
  next: "Continue",
  back: "Back",
  finish: "Finish setup",
  orDemo: "Or explore with demo rooms first",
};

export const common = {
  save: "Save",
  cancel: "Cancel",
  remove: "Remove",
  edit: "Edit",
  add: "Add",
  loading: "Loading…",
  errorTitle: "Something went wrong",
  errorBody: "We could not load this just now. Try again in a moment.",
  notFound: "We could not find that page.",
  retry: "Try again",
};

export const checkinSettings = {
  title: "Guest check-in",
  body: "Choose how guests confirm who they are when they check themselves in.",
  printQr: "Print QR card",
  openKiosk: "Open front-door kiosk",
  methods: {
    photo_id: "Photo ID check",
    last4: "Booking details check",
    self_declare: "Guest self-declaration",
  } as Record<string, string>,
  methodHelp: {
    photo_id: "Guest photographs their ID. We read the name, keep only the result and never store the photo.",
    last4: "Guest enters the last 4 of their booking reference or phone, or their email, whichever the booking has.",
    self_declare: "Always offered as the last resort so no one is stuck at the door. You'll get an alert to check ID in person.",
  } as Record<string, string>,
  primary: "Ask first",
  fallbackNote: "If the camera won't start or a guest needs more than 2 photo tries, Latchkey moves to the next option automatically.",
  listFlowNote: "ID checks are off: guests choose their platform, then pick their booking from a list showing first name and initial only.",
  saved: "Check-in settings saved",
  back: "Back to properties",
  print: "Print",
  cardHeadline: "Scan to check yourself in",
  cardOrVisit: "Or visit",
  cardPin: "Property PIN",
  qrAlt: "QR code for guest check-in",
};

export const alerts = {
  title: "Needs your attention",
  dismiss: "Mark as seen",
};

export const guest = {
  propertyName: "The Trinity Rooms",
  location: "High Wycombe",
  welcome: "Welcome to The Trinity Rooms",
  welcomeBody:
    "Check yourself in, find your room and ask for anything you need. It takes about a minute and there is nothing to download.",
  startCta: "Start check-in",
  helpCta: "I need help",
  stayWindow: (from: string, by: string) => `Rooms are ready from ${from}. Check-out is by ${by}.`,
  // Flow
  welcomeTo: (name: string) => `Welcome to ${name}.`,
  letsCheckIn: "Let's get you checked in.",
  back: "Back",
  startAgain: "Start again",
  stepLetter: "What does your surname start with?",
  stepLetterHint: "Your family name, as on your booking.",
  stepCheckout: "Which day do you check out?",
  stepPlatform: "Where did you book?",
  stepPickBooking: "Which booking is yours?",
  noArrivals: "We can't see any arrivals on that platform today. Please try another, or call your host.",
  platforms: {
    airbnb: "Airbnb",
    booking_com: "Booking.com",
    homestay: "Homestay.com",
    direct: "Booked directly",
    other: "Somewhere else",
  } as Record<string, string>,
  noMatchTitle: "We couldn't find that booking",
  noMatchBody: "Please check your answers and try again. If it still doesn't work, your host is happy to help.",
  welcomeBack: (name: string) => `Welcome back, ${name}`,
  welcomeBackBody:
    "You're already checked in. Just confirm it's you and we'll open your stay guide, where you can reread the house rules or ask for anything you need.",
  lockedTitle: "Let's pause for a moment",
  lockedBody: (time: string) =>
    `We've let your host know you're here. You can try again at ${time}, or give them a call.`,
  callHost: "Call your host",
  hi: (name: string) => `Hi ${name}`,
  confirmBody: "Is this your booking?",
  confirmYes: "Yes, that's me",
  confirmNo: "No, start again",
  idTitle: "A quick ID check",
  idConsent:
    "We only check your name matches your booking. We don't keep a copy of your ID.",
  idConsentAgree: "I'm happy to continue",
  idUseOther: "Use another way",
  idCameraHelp: "Hold your passport, driving licence or ID card flat, with the name clearly visible.",
  idTakePhoto: "Take photo",
  idChecking: "Checking your name…",
  idRetry: (left: number) =>
    `We couldn't read that clearly. Try again with more light and less glare (${left} ${left === 1 ? "try" : "tries"} left).`,
  idCameraFailed: "The camera didn't start, so let's try another way.",
  last4Title: "Confirm a few details",
  last4Kinds: {
    reference: "Last 4 characters of your booking reference",
    phone: "Last 4 digits of the phone number on your booking",
    email: "The email address on your booking",
  } as Record<string, string>,
  last4Submit: "Check",
  last4Retry: (left: number) => `That doesn't match. ${left} ${left === 1 ? "try" : "tries"} left.`,
  selfTitle: "Nearly there",
  selfBody: "Please confirm you are the guest named on this booking.",
  selfConfirm: "I confirm I'm the guest on this booking",
  selfNote:
    "Thank you. Your host will say hello and check your ID in person during your stay. Nothing more to do for now.",
  continue: "Continue",
  doneTitle: (name: string) => `You're all checked in, ${name}`,
  roomLine: (room: string, title: string | null) => `You're in ${room}${title ? `, ${title}` : ""}.`,
  noRoom: "Your host will show you to your room.",
  stayGuideCta: "Your stay guide",
  kioskResetting: "Starting over for the next guest…",
  kioskExitTitle: "Host access",
  kioskExitBody: "Enter the door PIN to leave kiosk mode.",
  kioskExitCta: "Unlock",
  kioskWrongPin: "That PIN isn't right.",
  pinTitle: "Enter the property PIN",
  pinBody: "You'll find the 6-digit PIN in your booking message or by the front door.",
  pinWrong: "We couldn't find a property with that PIN.",
  clear: "Clear",
  backspace: "Delete last digit",
  notFound: "We couldn't find that property. Please check the link or ask your host.",
  error: "Something went wrong. Please try again, or call your host.",
  // Stay page
  stayTitle: (name: string) => `Welcome, ${name}`,
  stayWifi: "Wi-Fi",
  stayNetwork: "Network",
  stayPassword: "Password",
  stayCheckout: "Check-out",
  stayQuiet: "Quiet hours",
  stayParking: "Parking",
  stayHost: "Your host",
  stayRules: "House rules",
  stayRulesList: ["Shoes off indoors, please.", "Please keep the shared kitchenette tidy."],
  stayGone: "This stay link has expired. We hope you enjoyed your stay.",
  // Carrying on somewhere else
  qrHeading: "Carry on with your phone",
  qrBlurb: "Point your camera at this square. You will pick up exactly where you are now.",
  qrDoneHeading: "Your room details",
  qrDoneBlurb: "Scan this to keep your door code, Wi-Fi and house notes on your phone.",
  qrSwitch: "Use another phone",
  qrOpen: "Show a square to scan with another phone",
  qrAlt: "Square code to scan with a phone camera",
  qrResuming: "Picking up where you left off…",
  // Messages and past requests
  inboxTitle: "Messages",
  inboxOpen: "Messages and requests",
  inboxEmpty: "No messages yet. Write below and your host will see it.",
  inboxSend: "Send",
  inboxPlaceholder: "Type your message to your host",
  inboxSent: "Sent. Your host has been told.",
  inboxHistory: "What you have asked for",
  inboxHistoryEmpty: "Nothing yet.",
  inboxYou: "You",
  inboxHost: "Your host",
};


export const hostPlaceholders = {
  comingSoon: "Coming in a later stage",
};

export const services = {
  title: "Services",
  subtitle: "Guest requests, problems and maintenance, and where to find someone to do the work.",
  tabInbox: "Requests",
  tabScheduled: "Maintenance",
  tabProviders: "Grow your listing",
  emptyInbox: "No requests yet. When a guest asks for something on their stay page, it lands here.",
  emptyScheduled: "No maintenance booked. Plan a boiler service, deep clean or handyman visit.",
  acknowledge: "Acknowledge",
  recommend: "Find someone",
  appoint: "Appoint",
  decline: "Decline",
  markDone: "Mark done",
  inProgress: "Start",
  recommendedTitle: "Who can come",
  noProviders:
    "Latchkey doesn't hold a list of trades. Open Find a trade to search the UK directories for this property's postcode.",
  bookMaintenance: "Book maintenance",
  demoBadge: "Demo",
  liveBadge: "Live",
  viewOnContra: "View profile",
  guestTold: "Guest has been told the arrival time.",
  statuses: {
    new: "New", acknowledged: "Acknowledged", booked: "Booked", in_progress: "In progress",
    done: "Done", declined: "Declined", cancelled: "Cancelled",
  } as Record<string, string>,
};

export const stayServices = {
  title: "Need something?",
  subtitle: "Tap what you need. Your host will confirm and tell you when it's coming.",
  issues: "Report a problem",
  extras: "Extras",
  notePlaceholder: "Anything we should know? (optional)",
  urgent: "It's urgent",
  send: "Send to host",
  sent: "Sent. Your host will be in touch here.",
  yourRequests: "Your requests",
  updates: "Updates from your host",
  expected: (t: string) => `Expected ${t}`,
  price: (p: string) => `${p}, paid to your host`,
  priceOnRequest: "Price confirmed by your host",
};

export const themeStudio = {
  title: "Look and feel",
  subtitle: "Brand your guest pages, kiosk and dashboard. Changes preview instantly.",
  presets: "Ready-made styles",
  colours: "Colours",
  primary: "Main colour",
  accent: "Highlight",
  background: "Background",
  surface: "Cards",
  foreground: "Text",
  fonts: "Fonts",
  heading: "Headings",
  body: "Body text",
  uploadFont: "Upload your own font (.ttf, .otf, .woff, .woff2)",
  logo: "Logo",
  uploadLogo: "Upload a logo",
  removeUpload: "Use a built-in logo",
  corners: "Corner roundness",
  link: "Your guest link",
  linkHelp: "Guests and you can bookmark this. It opens your fully branded page.",
  preview: "Preview",
  save: "Save look",
  saved: "Look saved",
};

export const integrations = {
  title: "Integrations: demo or live",
  subtitle: "Test each connection safely in demo mode, then switch it live when you're ready.",
  demo: "Demo",
  live: "Live",
  ready: "Ready",
  needsSetup: "Needs setup",
  items: {
    contra: { name: "Contra marketplace", demo: "Sample local freelancers, bookings confirm instantly.", live: "Searches and books real providers on Contra." },
    id_check: { name: "Photo ID reading", demo: "Any photo passes as a match, no AI call.", live: "AI reads the name on the ID and compares it." },
    host_email: { name: "Email alerts to you", demo: "Alerts show on Today only.", live: "Also emails you. Needs a sender email address." },
    guest_messages: { name: "Guest updates", demo: "Updates show on the guest's stay page.", live: "Stay page plus email to the guest when a sender address is set up." },
  },
  saved: "Switches saved",
};

export const guideCopy = {
  navLabel: "Guides",
  title: "Stay guides",
  subtitle: "Step-by-step guides guests see on their private link, from arrival day to check-out.",
  scopeHouse: "Whole house",
  scopeHelp: "House sections apply to every room. Pick a room to add its own version of a section.",
  modeLabel: "Guide style for this room",
  basic: "Basic",
  detailed: "Detailed",
  basicHelp: "Basic shows one short line per section, no photos. Detailed shows every step and photo.",
  summary: "Short summary (shown in basic and detailed)",
  addStep: "Add step",
  stepHeading: "Step title",
  stepBody: "What to do",
  addPhoto: "Add photo",
  removePhoto: "Remove photo",
  save: "Save section",
  saved: "Section saved",
  useHouse: "Use the house version",
  roomOwn: "This room has its own version",
  inherits: "Using the house version. Edit to give this room its own.",
  starterBadge: "Starter text: replace with your own",
  addStarter: "Add starter text",
  starterAdded: (n: number) => `Starter text added to ${n} sections`,
  doorLocked: (when: string) => `Door and lock details appear here from ${when}.`,
  readOnly: "Your stay has ended. This guide stays open for 24 hours in case you left something behind.",
  forgetTitle: "Things people usually forget",
  guideLink: "Copy guide link",
  guideLinkCopied: "Guide link copied. It opens on arrival day and stops at check-out.",
  notYet: (when: string) => `Your guide opens on ${when}. See you soon!`,
  photoAlt: (step: string) => `Photo: ${step}`,
  showMore: "More",
  showLess: "Less",
  amenitiesTitle: "Already in your room",
  amenitiesBody: "No need to ask for these — they're waiting for you.",
  pinLabel: "Show on the reminder card",
  pinHelp:
    "Pick the few things guests always forget. Whatever you pin appears in the card at the top of the guide, and is left out of the list below so it's never said twice.",
  pinnedBadge: "On the reminder card",
  pinLimit: "Four reminders is about as many as anyone reads.",
  orderTitle: "Running order",
  orderHelp: "Move sections so the guide reads the way you'd explain it in person.",
  moveUp: "Move up",
  moveDown: "Move down",
  orderSaved: "Order saved",
  amenitiesLabel: "What's already in this room",
  amenitiesHelp: "One per line, for example: Kettle, Hair dryer, Iron and board, Fresh towels.",
};

export const extrasCopy = {
  guestTitle: "Request extras",
  guestSubtitle: "Towels, late check-out, luggage storage and more. Free items cost nothing.",
  free: "Free",
  basket: "Your request",
  empty: "Tap items above to add them.",
  when: "When?",
  windows: { asap: "As soon as possible", evening: "This evening (18:00–21:00)", morning: "Tomorrow morning (08:00–10:00)", door: "Leave it outside my door" } as Record<string, string>,
  hostOut: (t: string) => `Your host is out until ${t}`,
  lateTitle: "Late check-out",
  earlyTitle: "Early check-in",
  lateNone: "Not available: someone arrives in your room that day.",
  earlyNone: "Not available: someone leaves your room that day.",
  until: (t: string) => `Until ${t}`,
  from: (t: string) => `From ${t}`,
  bagSize: "Bag size",
  loanNote: "Please leave it in the room at check-out.",
  send: "Send request",
  sent: "Request sent",
  cartButton: (n: number, t: string) => `Basket · ${n} item${n === 1 ? "" : "s"}${t ? ` · ${t}` : ""}`,
  cartTitle: "Your basket",
  cartClose: "Keep browsing",
  cartEmpty: "Nothing in your basket yet. Tap items to add them.",
  cartRemove: "Remove",
  cartFreeNote: "Free items cost nothing — you can send them on their own.",
  payAndSend: "Send and pay",
  sendFree: "Send request",
  added: (name: string) => `${name} added to your basket`,
  payTitle: "Payment",
  payTrouble: "Card not working?",
  payTroubleBody:
    "You can pay your host directly instead. Nothing is confirmed until your host has the money, so please let them know.",
  payBank: "Pay by bank transfer",
  payCash: "Pay cash to the host",
  payBankTitle: "Bank transfer",
  payCashTitle: "Paying cash",
  payCashBody:
    "Hand the money to your host and they will confirm it here. Until then this request is not guaranteed.",
  payRefNote: (ref: string) => `Please use ${ref} as the payment reference.`,
  payChosenBank: "You have chosen to pay by bank transfer.",
  payChosenCash: "You have chosen to pay in cash.",
  payNotGuaranteed: "Not guaranteed until your host confirms payment.",
  noBankDetails: "Your host has not added bank details. Please speak to them.",
  receipt: "Receipt",
  receiptTitle: "Receipt",
  receiptFor: (p: string) => `${p}`,
  receiptNo: (n: string) => `Receipt ${n}`,
  receiptPrint: "Print or save as PDF",
  receiptEmail: "Email it to me",
  receiptEmailed: "Receipt emailed.",
  receiptEmailOff: "Email is not set up yet — please print or save this receipt instead.",
  receiptNoAddress: "We do not have an email address for you. Please print or save this receipt.",
  receiptPaidBy: { card: "Card", bank: "Bank transfer", cash: "Cash" } as Record<string, string>,
  receiptTotal: "Total paid",
  total: "Total",
  yours: "Your requests",
  payLeft: (m: number) => `${m} min left to pay`,
  accept: "Accept new time",
  cancel: "Cancel",
  suggested: (w: string) => `Your host suggested: ${w}`,
  statuses: {
    requested: "Waiting for host", approved: "Approved", awaiting_payment: "Awaiting payment", suggested: "New time suggested",
    confirmed: "Booked", delivered: "Delivered", declined: "Declined", cancelled: "Cancelled", expired: "Expired",
  } as Record<string, string>,
  // host
  priceList: "Extras price list",
  priceListSub: "What guests can request. Free items still need your OK unless auto-approve is on.",
  autoApprove: "Auto-approve",
  active: "Offered",
  max: "Max",
  units: { item: "each", hour: "per hour", bag_day: "per bag per day", pack: "per pack" } as Record<string, string>,
  money: "Tax, bank and availability",
  taxRegistered: "Registered for sales tax (e.g. VAT, GST)",
  taxLabel: "Tax name",
  taxRate: "Rate %",
  pricesInclude: "Prices include tax",
  bank: "Bank transfer details shown to guests (optional)",
  outUntil: "I'm out until (shown to guests next to 'As soon as possible')",
  save: "Save",
  saved: "Saved",
  inbox: "Extras requests",
  inboxEmpty: "No extras requests yet. When guests ask for towels or late check-out, they'll appear here.",
  approve: "Approve",
  decline: "Decline",
  suggest: "Suggest another time",
  delivered: "Mark delivered",
  markPaid: "Payment received",
  payingBank: "Guest is paying by bank transfer",
  payingCash: "Guest is paying cash",
};

/** Calendar connection help, validation messages and the outbound feed. */
export const calendarUi = {
  stepsChecked: "Steps last checked: Sep 2026",
  openHelp: "Open the platform's help page",
  howItWorks:
    "Latchkey checks this calendar every 30 minutes. Airbnb and Booking.com only share dates, and sometimes a reservation code, so you'll add guest names for some bookings on the Today page.",
  helpTitle: "Calendar help",
  helpSubtitle: "Where to find the calendar link on each platform.",
  managerTitle: "Channel manager API",
  managerBody:
    "Expedia and hotel-style listings connect through a channel manager rather than a calendar link. Direct connections are coming soon.",
  errors: {
    https: "The link must start with https://",
    notCalendar: "This link looks like a web page, not a calendar.",
    noEvents: "The link returned no events. Check you copied the export link, not the import box.",
  },
};

export const feedCopy = {
  title: "Share this room's Latchkey calendar",
  body:
    "Only needed if you take direct bookings in Latchkey. If your platforms already sync with each other, leave this off.",
  detail:
    "The feed includes direct bookings and whole-day blocks you created here. It never repeats bookings imported from a platform, and it doesn't include cleaning or late check-out times.",
  enable: "Share this calendar",
  copy: "Copy feed link",
  copied: "Feed link copied",
  regenerate: "Make a new link",
  regenerated: "New feed link created. Update it anywhere you pasted the old one.",
};

/** One-tap notes the host can send with a decision. */
export const responseNotes = {
  label: "Add a note for the guest",
  custom: "Write your own note",
  approve: ["Left outside your door", "Will bring it at 18:30", "Ready to collect from the hallway"],
  decline: ["Room needed for an arrival", "Sorry, we've run out today", "Outside our service hours"],
  suggest: ["This is the earliest I can manage", "Cleaner is in the house until then"],
  fromHost: (note: string) => `Note from your host: ${note}`,
  send: "Send",
};

/** Guest requests waiting on the host, shown on Today. */
export const todayRequests = {
  title: "Guest requests",
  empty: "No requests waiting.",
  viewAll: "See all requests",
  tightTurnaround: (mins: number) =>
    `Tight turnaround: only ${mins} minutes between check-out and the next arrival.`,
};

/** Adding and editing price list items. */
export const priceListUi = {
  addItem: "Add an item",
  editItem: "Edit item",
  name: "Name",
  price: "Price",
  isFree: "Free on request",
  unit: "Charged",
  maxQty: "Most a guest can ask for",
  isLoan: "Lent, not kept",
  moveUp: "Move up",
  moveDown: "Move down",
  remove: "Remove from the list",
  removeConfirm: "Remove this item? Past requests keep their details.",
  removed: "Item removed",
  added: "Item added",
};

/** Card payments through Stripe. */
export const payments = {
  title: "Card payments (Stripe)",
  body: "Guests pay for approved extras on their stay page. Latchkey stays the single price list; Stripe just takes the money.",
  notConnected: "Not connected",
  testBadge: "Test mode",
  liveBadge: "Live payments",
  connectedTo: (name: string) => `Connected to ${name}.`,
  webhookMissing: "Almost there: add the webhook signing secret so payments confirm automatically.",
  webhookTitle: "Add the payment webhook",
  webhookBody:
    "In Stripe, go to Developers > Webhooks > Add endpoint, paste the address below, tick checkout.session.completed, then save its signing secret in Latchkey as STRIPE_WEBHOOK_SECRET.",
  steps: [
    { title: "Create a Stripe account", body: "Sign up at stripe.com. You can take test payments straight away and switch to real ones after Stripe verifies your details." },
    { title: "Copy your key", body: "In Stripe, turn Test mode on, then go to Developers > API keys. A standard secret key (sk_) or a restricted key (rk_) both work, as long as the restricted key can write Checkout Sessions, Products, Prices and Payment Intents." },
    { title: "Save it in Latchkey", body: "Ask me to add it and I'll open a secure form. It is stored as STRIPE_SECRET_KEY and never shown in the app." },
  ],
  syncButton: "Send price list to Stripe",
  syncedCount: (n: number) => (n === 0 ? "No items sent to Stripe yet." : `${n} paid item${n === 1 ? "" : "s"} set up in Stripe.`),
  synced: (created: number, updated: number) => `Sent to Stripe: ${created} new, ${updated} updated.`,
  syncFailed: "Stripe wouldn't accept that. Check the key and try again.",
  payNow: "Pay now",
  payFailed: "We couldn't open the payment page. Please try again.",
  paidToast: "Thank you, that's paid and confirmed.",
};

/** Finding tradespeople for property work. */
export const trades = {
  tabLabel: "Find a trade",
  intro:
    "Pick what needs doing and Latchkey opens a ready-made search on the UK sites that vet and review tradespeople, using this property's own address. Latchkey doesn't copy their listings, so you always see live, up-to-date firms.",
  jobLabel: "What needs doing",
  termLabel: "Search words",
  areaLabel: "Postcode or town",
  needArea: "Add a postcode to this property, or type a town above, and the searches will open for that area.",
  searching: (term: string, area: string) => `Searching for “${term}” near ${area}.`,
  searchNow: (name: string) => `Search ${name} now`,
  openOn: (name: string) => `Search ${name}`,
  legalNote:
    "These sites don't offer a way to pull their listings into other apps, and copying them automatically isn't allowed, so Latchkey links out instead. Once you've found someone you like, add them to a job so their details stay with the property.",
  growthTitle: "Grow your listing",
  growthBody:
    "Contra is a marketplace for creative, tech and marketing freelancers. It's the right place for photography, listing copy, signage, a direct-booking site and marketing.",
  notMaintenance:
    "Contra has no cleaners, plumbers or electricians, so it's never used for guest problems or maintenance. Use Find a trade for those.",
  contraNote: "Each search opens on Contra in a new tab with the words already filled in.",
};

export const hostInbox = {
  title: "Guest messages",
  open: "Open guest messages",
  empty: "No guest messages yet. Anything a guest sends from their stay page lands here.",
  pick: "Choose a guest to read the conversation.",
  back: "All conversations",
  placeholder: "Reply to your guest",
  send: "Send reply",
  unreadOne: "1 unread message",
  unreadMany: (n: number) => `${n} unread messages`,
};

export const tradesCopy = {
  title: "Your trades and helpers",
  blurb:
    "Your own list of people you actually call. One tap to ring, text, WhatsApp or email them from this device.",
  empty: "No contacts yet. Add someone, bring in a spreadsheet, or let Latchkey suggest who you'll need.",
  add: "Add a contact",
  edit: "Edit contact",
  importCta: "Import a spreadsheet",
  importTitle: "Import contacts",
  importBlurb: "Drop in a CSV from your phone, email or accountant. You'll check the columns before anything is saved.",
  importChoose: "Choose a CSV file",
  importMap: "Match your columns",
  importPreview: (n: number) => `${n} contact${n === 1 ? "" : "s"} ready to add`,
  importSkipped: (n: number) => `${n} row${n === 1 ? "" : "s"} skipped — no name or no way to contact them.`,
  importConfirm: "Add these contacts",
  importIgnore: "Ignore this column",
  suggestCta: "Suggest who I'll need",
  suggestAgain: "Suggest again",
  suggestBlurb:
    "Uses a little AI to list the trades a place like yours usually needs nearby. It never invents phone numbers — you add the real ones.",
  suggestDone: "Already suggested for this property.",
  suggestions: "Suggested for this property",
  suggestAdd: "Add to my list",
  searchFor: (role: string) => `Find a ${role.toLowerCase()}`,
  call: "Call",
  text: "Text",
  whatsapp: "WhatsApp",
  email: "Email",
  preferred: "First call",
  noneForJob: "No saved contacts yet. Add someone in the address book above, or search the directories below.",
  noContact: "No number or email saved yet.",
  deleteConfirm: "Remove this contact?",
  fields: {
    name: "Name",
    company_name: "Company",
    category: "What they do",
    phone: "Phone",
    whatsapp_phone: "WhatsApp number (if different)",
    email: "Email",
    website: "Website",
    area: "Area they cover",
    notes: "Notes",
    is_preferred: "Call this one first",
  },
  save: "Save contact",
  cancel: "Cancel",
  remove: "Remove",
};

export const pricingCopy = {
  eyebrow: "Pricing",
  title: (days: number) => `Free for ${days} days, then pennies a month`,
  base: (v: string) => `${v} a month for your first property and room`,
  room: (v: string) => `${v} a month for each extra room`,
  property: (v: string) => `${v} a month for each extra property`,
  guarantee: "Money-back guarantee if it isn't for you",
  cta: (days: number) => `Start your ${days}-day free trial`,
  estimator: "What would I pay?",
  properties: "Properties",
  roomsEach: "Rooms in each",
  after: (days: number) => `After your ${days}-day free trial`,
  perMonth: "a month",
  demoTitle: "Like what you see? Run your own rooms this way.",
  demoBody: (days: number) => `Register as a host and try Latchkey free for ${days} days, with a money-back guarantee.`,
  adminTitle: "Subscription pricing (super admin)",
  adminBody: "Amounts in pence. Changes show on the home page straight away.",
  saved: "Pricing saved",
};
