/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as PDemoRouteImport } from './routes/p.demo'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppBookingsRouteImport } from './routes/_authenticated/app.bookings'
import { Route as AuthenticatedAppConnectionsRouteImport } from './routes/_authenticated/app.connections'
import { Route as AuthenticatedAppPropertiesRouteImport } from './routes/_authenticated/app.properties'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppSetupRouteImport } from './routes/_authenticated/app.setup'
import { Route as AuthenticatedAppTodayRouteImport } from './routes/_authenticated/app.today'
import { Route as ApiPublicCronLatchkeyRouteImport } from './routes/api/public/cron/latchkey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PDemoRoute = PDemoRouteImport.update({
  id: '/p/demo',
  path: '/p/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBookingsRoute =
  AuthenticatedAppBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConnectionsRoute =
  AuthenticatedAppConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPropertiesRoute =
  AuthenticatedAppPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSetupRoute = AuthenticatedAppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTodayRoute = AuthenticatedAppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicCronLatchkeyRoute = ApiPublicCronLatchkeyRouteImport.update({
  id: '/api/public/cron/latchkey',
  path: '/api/public/cron/latchkey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/p/demo': typeof PDemoRoute
  '/app/bookings': typeof AuthenticatedAppBookingsRoute
  '/app/connections': typeof AuthenticatedAppConnectionsRoute
  '/app/properties': typeof AuthenticatedAppPropertiesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/setup': typeof AuthenticatedAppSetupRoute
  '/app/today': typeof AuthenticatedAppTodayRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/cron/latchkey': typeof ApiPublicCronLatchkeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/p/demo': typeof PDemoRoute
  '/app/bookings': typeof AuthenticatedAppBookingsRoute
  '/app/connections': typeof AuthenticatedAppConnectionsRoute
  '/app/properties': typeof AuthenticatedAppPropertiesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/setup': typeof AuthenticatedAppSetupRoute
  '/app/today': typeof AuthenticatedAppTodayRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/public/cron/latchkey': typeof ApiPublicCronLatchkeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/p/demo': typeof PDemoRoute
  '/_authenticated/app/bookings': typeof AuthenticatedAppBookingsRoute
  '/_authenticated/app/connections': typeof AuthenticatedAppConnectionsRoute
  '/_authenticated/app/properties': typeof AuthenticatedAppPropertiesRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/setup': typeof AuthenticatedAppSetupRoute
  '/_authenticated/app/today': typeof AuthenticatedAppTodayRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/cron/latchkey': typeof ApiPublicCronLatchkeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/p/demo'
    | '/app/bookings'
    | '/app/connections'
    | '/app/properties'
    | '/app/settings'
    | '/app/setup'
    | '/app/today'
    | '/app/'
    | '/api/public/cron/latchkey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/p/demo'
    | '/app/bookings'
    | '/app/connections'
    | '/app/properties'
    | '/app/settings'
    | '/app/setup'
    | '/app/today'
    | '/app'
    | '/api/public/cron/latchkey'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/p/demo'
    | '/_authenticated/app/bookings'
    | '/_authenticated/app/connections'
    | '/_authenticated/app/properties'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/setup'
    | '/_authenticated/app/today'
    | '/_authenticated/app/'
    | '/api/public/cron/latchkey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PDemoRoute: typeof PDemoRoute
  ApiPublicCronLatchkeyRoute: typeof ApiPublicCronLatchkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/p/demo': {
      id: '/p/demo'
      path: '/p/demo'
      fullPath: '/p/demo'
      preLoaderRoute: typeof PDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bookings': {
      id: '/_authenticated/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AuthenticatedAppBookingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/connections': {
      id: '/_authenticated/app/connections'
      path: '/connections'
      fullPath: '/app/connections'
      preLoaderRoute: typeof AuthenticatedAppConnectionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/properties': {
      id: '/_authenticated/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AuthenticatedAppPropertiesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/setup': {
      id: '/_authenticated/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AuthenticatedAppSetupRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/today': {
      id: '/_authenticated/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AuthenticatedAppTodayRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/cron/latchkey': {
      id: '/api/public/cron/latchkey'
      path: '/api/public/cron/latchkey'
      fullPath: '/api/public/cron/latchkey'
      preLoaderRoute: typeof ApiPublicCronLatchkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBookingsRoute: typeof AuthenticatedAppBookingsRoute
  AuthenticatedAppConnectionsRoute: typeof AuthenticatedAppConnectionsRoute
  AuthenticatedAppPropertiesRoute: typeof AuthenticatedAppPropertiesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSetupRoute: typeof AuthenticatedAppSetupRoute
  AuthenticatedAppTodayRoute: typeof AuthenticatedAppTodayRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBookingsRoute: AuthenticatedAppBookingsRoute,
  AuthenticatedAppConnectionsRoute: AuthenticatedAppConnectionsRoute,
  AuthenticatedAppPropertiesRoute: AuthenticatedAppPropertiesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSetupRoute: AuthenticatedAppSetupRoute,
  AuthenticatedAppTodayRoute: AuthenticatedAppTodayRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PDemoRoute: PDemoRoute,
  ApiPublicCronLatchkeyRoute: ApiPublicCronLatchkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
