/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBookingsRouteImport } from './routes/app.bookings'
import { Route as AppConnectionsRouteImport } from './routes/app.connections'
import { Route as AppPropertiesRouteImport } from './routes/app.properties'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTodayRouteImport } from './routes/app.today'
import { Route as PDemoRouteImport } from './routes/p.demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const PDemoRoute = PDemoRouteImport.update({
  id: '/p/demo',
  path: '/p/demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bookings': typeof AppBookingsRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/properties': typeof AppPropertiesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/today': typeof AppTodayRoute
  '/p/demo': typeof PDemoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/properties': typeof AppPropertiesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/today': typeof AppTodayRoute
  '/p/demo': typeof PDemoRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bookings': typeof AppBookingsRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/properties': typeof AppPropertiesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/today': typeof AppTodayRoute
  '/p/demo': typeof PDemoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/bookings'
    | '/app/connections'
    | '/app/properties'
    | '/app/settings'
    | '/app/today'
    | '/p/demo'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/bookings'
    | '/app/connections'
    | '/app/properties'
    | '/app/settings'
    | '/app/today'
    | '/p/demo'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/bookings'
    | '/app/connections'
    | '/app/properties'
    | '/app/settings'
    | '/app/today'
    | '/p/demo'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PDemoRoute: typeof PDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings': {
      id: '/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connections': {
      id: '/app/connections'
      path: '/connections'
      fullPath: '/app/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties': {
      id: '/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/today': {
      id: '/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/p/demo': {
      id: '/p/demo'
      path: '/p/demo'
      fullPath: '/p/demo'
      preLoaderRoute: typeof PDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBookingsRoute: typeof AppBookingsRoute
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppPropertiesRoute: typeof AppPropertiesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTodayRoute: typeof AppTodayRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookingsRoute: AppBookingsRoute,
  AppConnectionsRoute: AppConnectionsRoute,
  AppPropertiesRoute: AppPropertiesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTodayRoute: AppTodayRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PDemoRoute: PDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
