/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as KioskCodeRouteImport } from './routes/kiosk.$code'
import { Route as PCodeRouteImport } from './routes/p.$code'
import { Route as PDemoRouteImport } from './routes/p.demo'
import { Route as StayTokenRouteImport } from './routes/stay.$token'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppBookingsRouteImport } from './routes/_authenticated/app.bookings'
import { Route as AuthenticatedAppConnectionsRouteImport } from './routes/_authenticated/app.connections'
import { Route as AuthenticatedAppGuidesRouteImport } from './routes/_authenticated/app.guides'
import { Route as AuthenticatedAppPropertiesRouteImport } from './routes/_authenticated/app.properties'
import { Route as AuthenticatedAppServicesRouteImport } from './routes/_authenticated/app.services'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppSetupRouteImport } from './routes/_authenticated/app.setup'
import { Route as AuthenticatedAppTodayRouteImport } from './routes/_authenticated/app.today'
import { Route as AuthenticatedAppPrintPropertyIdRouteImport } from './routes/_authenticated/app.print.$propertyId'
import { Route as ApiPublicCalendarTokenRouteImport } from './routes/api/public/calendar.$token'
import { Route as ApiPublicCronLatchkeyRouteImport } from './routes/api/public/cron/latchkey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const KioskCodeRoute = KioskCodeRouteImport.update({
  id: '/kiosk/$code',
  path: '/kiosk/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PCodeRoute = PCodeRouteImport.update({
  id: '/p/$code',
  path: '/p/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PDemoRoute = PDemoRouteImport.update({
  id: '/p/demo',
  path: '/p/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const StayTokenRoute = StayTokenRouteImport.update({
  id: '/stay/$token',
  path: '/stay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBookingsRoute =
  AuthenticatedAppBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConnectionsRoute =
  AuthenticatedAppConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGuidesRoute = AuthenticatedAppGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPropertiesRoute =
  AuthenticatedAppPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppServicesRoute =
  AuthenticatedAppServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSetupRoute = AuthenticatedAppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTodayRoute = AuthenticatedAppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPrintPropertyIdRoute =
  AuthenticatedAppPrintPropertyIdRouteImport.update({
    id: '/print/$propertyId',
    path: '/print/$propertyId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicCalendarTokenRoute = ApiPublicCalendarTokenRouteImport.update({
  id: '/api/public/calendar/$token',
  path: '/api/public/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronLatchkeyRoute = ApiPublicCronLatchkeyRouteImport.update({
  id: '/api/public/cron/latchkey',
  path: '/api/public/cron/latchkey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/kiosk/$code': typeof KioskCodeRoute
  '/p/$code': typeof PCodeRoute
  '/p/demo': typeof PDemoRoute
  '/stay/$token': typeof StayTokenRoute
  '/app/bookings': typeof AuthenticatedAppBookingsRoute
  '/app/connections': typeof AuthenticatedAppConnectionsRoute
  '/app/guides': typeof AuthenticatedAppGuidesRoute
  '/app/properties': typeof AuthenticatedAppPropertiesRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/setup': typeof AuthenticatedAppSetupRoute
  '/app/today': typeof AuthenticatedAppTodayRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/print/$propertyId': typeof AuthenticatedAppPrintPropertyIdRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/cron/latchkey': typeof ApiPublicCronLatchkeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/kiosk/$code': typeof KioskCodeRoute
  '/p/$code': typeof PCodeRoute
  '/p/demo': typeof PDemoRoute
  '/stay/$token': typeof StayTokenRoute
  '/app/bookings': typeof AuthenticatedAppBookingsRoute
  '/app/connections': typeof AuthenticatedAppConnectionsRoute
  '/app/guides': typeof AuthenticatedAppGuidesRoute
  '/app/properties': typeof AuthenticatedAppPropertiesRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/setup': typeof AuthenticatedAppSetupRoute
  '/app/today': typeof AuthenticatedAppTodayRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/print/$propertyId': typeof AuthenticatedAppPrintPropertyIdRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/cron/latchkey': typeof ApiPublicCronLatchkeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/kiosk/$code': typeof KioskCodeRoute
  '/p/$code': typeof PCodeRoute
  '/p/demo': typeof PDemoRoute
  '/stay/$token': typeof StayTokenRoute
  '/_authenticated/app/bookings': typeof AuthenticatedAppBookingsRoute
  '/_authenticated/app/connections': typeof AuthenticatedAppConnectionsRoute
  '/_authenticated/app/guides': typeof AuthenticatedAppGuidesRoute
  '/_authenticated/app/properties': typeof AuthenticatedAppPropertiesRoute
  '/_authenticated/app/services': typeof AuthenticatedAppServicesRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/setup': typeof AuthenticatedAppSetupRoute
  '/_authenticated/app/today': typeof AuthenticatedAppTodayRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/print/$propertyId': typeof AuthenticatedAppPrintPropertyIdRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/cron/latchkey': typeof ApiPublicCronLatchkeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/checkin'
    | '/app'
    | '/kiosk/$code'
    | '/p/$code'
    | '/p/demo'
    | '/stay/$token'
    | '/app/bookings'
    | '/app/connections'
    | '/app/guides'
    | '/app/properties'
    | '/app/services'
    | '/app/settings'
    | '/app/setup'
    | '/app/today'
    | '/app/'
    | '/app/print/$propertyId'
    | '/api/public/calendar/$token'
    | '/api/public/cron/latchkey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/checkin'
    | '/kiosk/$code'
    | '/p/$code'
    | '/p/demo'
    | '/stay/$token'
    | '/app/bookings'
    | '/app/connections'
    | '/app/guides'
    | '/app/properties'
    | '/app/services'
    | '/app/settings'
    | '/app/setup'
    | '/app/today'
    | '/app'
    | '/app/print/$propertyId'
    | '/api/public/calendar/$token'
    | '/api/public/cron/latchkey'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/auth'
    | '/checkin'
    | '/_authenticated/app'
    | '/kiosk/$code'
    | '/p/$code'
    | '/p/demo'
    | '/stay/$token'
    | '/_authenticated/app/bookings'
    | '/_authenticated/app/connections'
    | '/_authenticated/app/guides'
    | '/_authenticated/app/properties'
    | '/_authenticated/app/services'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/setup'
    | '/_authenticated/app/today'
    | '/_authenticated/app/'
    | '/_authenticated/app/print/$propertyId'
    | '/api/public/calendar/$token'
    | '/api/public/cron/latchkey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  CheckinRoute: typeof CheckinRoute
  KioskCodeRoute: typeof KioskCodeRoute
  PCodeRoute: typeof PCodeRoute
  PDemoRoute: typeof PDemoRoute
  StayTokenRoute: typeof StayTokenRoute
  ApiPublicCalendarTokenRoute: typeof ApiPublicCalendarTokenRoute
  ApiPublicCronLatchkeyRoute: typeof ApiPublicCronLatchkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/kiosk/$code': {
      id: '/kiosk/$code'
      path: '/kiosk/$code'
      fullPath: '/kiosk/$code'
      preLoaderRoute: typeof KioskCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$code': {
      id: '/p/$code'
      path: '/p/$code'
      fullPath: '/p/$code'
      preLoaderRoute: typeof PCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/demo': {
      id: '/p/demo'
      path: '/p/demo'
      fullPath: '/p/demo'
      preLoaderRoute: typeof PDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stay/$token': {
      id: '/stay/$token'
      path: '/stay/$token'
      fullPath: '/stay/$token'
      preLoaderRoute: typeof StayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bookings': {
      id: '/_authenticated/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AuthenticatedAppBookingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/connections': {
      id: '/_authenticated/app/connections'
      path: '/connections'
      fullPath: '/app/connections'
      preLoaderRoute: typeof AuthenticatedAppConnectionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/guides': {
      id: '/_authenticated/app/guides'
      path: '/guides'
      fullPath: '/app/guides'
      preLoaderRoute: typeof AuthenticatedAppGuidesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/properties': {
      id: '/_authenticated/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AuthenticatedAppPropertiesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/services': {
      id: '/_authenticated/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AuthenticatedAppServicesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/setup': {
      id: '/_authenticated/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AuthenticatedAppSetupRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/today': {
      id: '/_authenticated/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AuthenticatedAppTodayRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/print/$propertyId': {
      id: '/_authenticated/app/print/$propertyId'
      path: '/print/$propertyId'
      fullPath: '/app/print/$propertyId'
      preLoaderRoute: typeof AuthenticatedAppPrintPropertyIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/calendar/$token': {
      id: '/api/public/calendar/$token'
      path: '/api/public/calendar/$token'
      fullPath: '/api/public/calendar/$token'
      preLoaderRoute: typeof ApiPublicCalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/latchkey': {
      id: '/api/public/cron/latchkey'
      path: '/api/public/cron/latchkey'
      fullPath: '/api/public/cron/latchkey'
      preLoaderRoute: typeof ApiPublicCronLatchkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBookingsRoute: typeof AuthenticatedAppBookingsRoute
  AuthenticatedAppConnectionsRoute: typeof AuthenticatedAppConnectionsRoute
  AuthenticatedAppGuidesRoute: typeof AuthenticatedAppGuidesRoute
  AuthenticatedAppPropertiesRoute: typeof AuthenticatedAppPropertiesRoute
  AuthenticatedAppServicesRoute: typeof AuthenticatedAppServicesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSetupRoute: typeof AuthenticatedAppSetupRoute
  AuthenticatedAppTodayRoute: typeof AuthenticatedAppTodayRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppPrintPropertyIdRoute: typeof AuthenticatedAppPrintPropertyIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBookingsRoute: AuthenticatedAppBookingsRoute,
  AuthenticatedAppConnectionsRoute: AuthenticatedAppConnectionsRoute,
  AuthenticatedAppGuidesRoute: AuthenticatedAppGuidesRoute,
  AuthenticatedAppPropertiesRoute: AuthenticatedAppPropertiesRoute,
  AuthenticatedAppServicesRoute: AuthenticatedAppServicesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSetupRoute: AuthenticatedAppSetupRoute,
  AuthenticatedAppTodayRoute: AuthenticatedAppTodayRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppPrintPropertyIdRoute: AuthenticatedAppPrintPropertyIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  CheckinRoute: CheckinRoute,
  KioskCodeRoute: KioskCodeRoute,
  PCodeRoute: PCodeRoute,
  PDemoRoute: PDemoRoute,
  StayTokenRoute: StayTokenRoute,
  ApiPublicCalendarTokenRoute: ApiPublicCalendarTokenRoute,
  ApiPublicCronLatchkeyRoute: ApiPublicCronLatchkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
